; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=instcombine < %s | FileCheck %s

target triple = "aarch64-unknown-linux-gnu"

define <vscale x 2 x i64> @mul_i64_by_2_commuted(<vscale x 2 x i64> %x) {
; CHECK-LABEL: define <vscale x 2 x i64> @mul_i64_by_2_commuted(
; CHECK-SAME: <vscale x 2 x i64> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = shl <vscale x 2 x i64> [[X]], splat (i64 1)
; CHECK-NEXT:    ret <vscale x 2 x i64> [[OUT]]
;
  %out = mul <vscale x 2 x i64> splat(i64 2), %x
  ret <vscale x 2 x i64> %out
}

define <vscale x 2 x i64> @mul_i64_by_3_commuted(<vscale x 2 x i64> %x) {
; CHECK-LABEL: define <vscale x 2 x i64> @mul_i64_by_3_commuted(
; CHECK-SAME: <vscale x 2 x i64> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = mul <vscale x 2 x i64> [[X]], splat (i64 3)
; CHECK-NEXT:    ret <vscale x 2 x i64> [[OUT]]
;
  %out = mul <vscale x 2 x i64> splat(i64 3), %x
  ret <vscale x 2 x i64> %out
}

define <vscale x 2 x i64> @mul_i64_by_5_commuted(<vscale x 2 x i64> %x) {
; CHECK-LABEL: define <vscale x 2 x i64> @mul_i64_by_5_commuted(
; CHECK-SAME: <vscale x 2 x i64> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = mul <vscale x 2 x i64> [[X]], splat (i64 5)
; CHECK-NEXT:    ret <vscale x 2 x i64> [[OUT]]
;
  %out = mul <vscale x 2 x i64> splat(i64 5), %x
  ret <vscale x 2 x i64> %out
}

define <vscale x 2 x i64> @mul_i64_by_9_commuted(<vscale x 2 x i64> %x) {
; CHECK-LABEL: define <vscale x 2 x i64> @mul_i64_by_9_commuted(
; CHECK-SAME: <vscale x 2 x i64> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = mul <vscale x 2 x i64> [[X]], splat (i64 9)
; CHECK-NEXT:    ret <vscale x 2 x i64> [[OUT]]
;
  %out = mul <vscale x 2 x i64> splat(i64 9), %x
  ret <vscale x 2 x i64> %out
}

define <vscale x 2 x i64> @mla_i64_by_2_commuted(<vscale x 2 x i64> %a, <vscale x 2 x i64> %x) {
; CHECK-LABEL: define <vscale x 2 x i64> @mla_i64_by_2_commuted(
; CHECK-SAME: <vscale x 2 x i64> [[A:%.*]], <vscale x 2 x i64> [[X:%.*]]) {
; CHECK-NEXT:    [[MUL:%.*]] = shl <vscale x 2 x i64> [[X]], splat (i64 1)
; CHECK-NEXT:    [[OUT:%.*]] = add <vscale x 2 x i64> [[A]], [[MUL]]
; CHECK-NEXT:    ret <vscale x 2 x i64> [[OUT]]
;
  %mul = mul <vscale x 2 x i64> splat(i64 2), %x
  %out = add <vscale x 2 x i64> %a, %mul
  ret <vscale x 2 x i64> %out
}

define <vscale x 2 x i64> @mla_i64_by_4_commuted(<vscale x 2 x i64> %a, <vscale x 2 x i64> %x) {
; CHECK-LABEL: define <vscale x 2 x i64> @mla_i64_by_4_commuted(
; CHECK-SAME: <vscale x 2 x i64> [[A:%.*]], <vscale x 2 x i64> [[X:%.*]]) {
; CHECK-NEXT:    [[MUL:%.*]] = shl <vscale x 2 x i64> [[X]], splat (i64 2)
; CHECK-NEXT:    [[OUT:%.*]] = add <vscale x 2 x i64> [[A]], [[MUL]]
; CHECK-NEXT:    ret <vscale x 2 x i64> [[OUT]]
;
  %mul = mul <vscale x 2 x i64> splat(i64 4), %x
  %out = add <vscale x 2 x i64> %a, %mul
  ret <vscale x 2 x i64> %out
}

define <vscale x 2 x i64> @mla_i64_by_8_commuted(<vscale x 2 x i64> %a, <vscale x 2 x i64> %x) {
; CHECK-LABEL: define <vscale x 2 x i64> @mla_i64_by_8_commuted(
; CHECK-SAME: <vscale x 2 x i64> [[A:%.*]], <vscale x 2 x i64> [[X:%.*]]) {
; CHECK-NEXT:    [[MUL:%.*]] = shl <vscale x 2 x i64> [[X]], splat (i64 3)
; CHECK-NEXT:    [[OUT:%.*]] = add <vscale x 2 x i64> [[A]], [[MUL]]
; CHECK-NEXT:    ret <vscale x 2 x i64> [[OUT]]
;
  %mul = mul <vscale x 2 x i64> splat(i64 8), %x
  %out = add <vscale x 2 x i64> %a, %mul
  ret <vscale x 2 x i64> %out
}

define <vscale x 4 x i32> @svmul_u_i32_by_2_commuted(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %x) {
; CHECK-LABEL: define <vscale x 4 x i32> @svmul_u_i32_by_2_commuted(
; CHECK-SAME: <vscale x 4 x i1> [[PG:%.*]], <vscale x 4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1> [[PG]], <vscale x 4 x i32> [[X]], <vscale x 4 x i32> splat (i32 2))
; CHECK-NEXT:    ret <vscale x 4 x i32> [[OUT]]
;
  %out = call <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> splat(i32 2), <vscale x 4 x i32> %x)
  ret <vscale x 4 x i32> %out
}

define <vscale x 4 x i32> @svmul_u_i32_by_3_commuted(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %x) {
; CHECK-LABEL: define <vscale x 4 x i32> @svmul_u_i32_by_3_commuted(
; CHECK-SAME: <vscale x 4 x i1> [[PG:%.*]], <vscale x 4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1> [[PG]], <vscale x 4 x i32> [[X]], <vscale x 4 x i32> splat (i32 3))
; CHECK-NEXT:    ret <vscale x 4 x i32> [[OUT]]
;
  %out = call <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> splat(i32 3), <vscale x 4 x i32> %x)
  ret <vscale x 4 x i32> %out
}

define <vscale x 4 x i32> @svmul_u_i32_by_5_commuted(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %x) {
; CHECK-LABEL: define <vscale x 4 x i32> @svmul_u_i32_by_5_commuted(
; CHECK-SAME: <vscale x 4 x i1> [[PG:%.*]], <vscale x 4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1> [[PG]], <vscale x 4 x i32> [[X]], <vscale x 4 x i32> splat (i32 5))
; CHECK-NEXT:    ret <vscale x 4 x i32> [[OUT]]
;
  %out = call <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> splat(i32 5), <vscale x 4 x i32> %x)
  ret <vscale x 4 x i32> %out
}

define <vscale x 4 x i32> @svmul_u_i32_by_9_commuted(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %x) {
; CHECK-LABEL: define <vscale x 4 x i32> @svmul_u_i32_by_9_commuted(
; CHECK-SAME: <vscale x 4 x i1> [[PG:%.*]], <vscale x 4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1> [[PG]], <vscale x 4 x i32> [[X]], <vscale x 4 x i32> splat (i32 9))
; CHECK-NEXT:    ret <vscale x 4 x i32> [[OUT]]
;
  %out = call <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> splat(i32 9), <vscale x 4 x i32> %x)
  ret <vscale x 4 x i32> %out
}

define <vscale x 4 x i32> @svmla_u_i32_by_2_commuted(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x) {
; CHECK-LABEL: define <vscale x 4 x i32> @svmla_u_i32_by_2_commuted(
; CHECK-SAME: <vscale x 4 x i1> [[PG:%.*]], <vscale x 4 x i32> [[A:%.*]], <vscale x 4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.mla.u.nxv4i32(<vscale x 4 x i1> [[PG]], <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X]], <vscale x 4 x i32> splat (i32 2))
; CHECK-NEXT:    ret <vscale x 4 x i32> [[OUT]]
;
  %out = call <vscale x 4 x i32> @llvm.aarch64.sve.mla.u.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> splat(i32 2), <vscale x 4 x i32> %x)
  ret <vscale x 4 x i32> %out
}

define <vscale x 4 x i32> @svmla_u_i32_by_4_commuted(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x) {
; CHECK-LABEL: define <vscale x 4 x i32> @svmla_u_i32_by_4_commuted(
; CHECK-SAME: <vscale x 4 x i1> [[PG:%.*]], <vscale x 4 x i32> [[A:%.*]], <vscale x 4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.mla.u.nxv4i32(<vscale x 4 x i1> [[PG]], <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X]], <vscale x 4 x i32> splat (i32 4))
; CHECK-NEXT:    ret <vscale x 4 x i32> [[OUT]]
;
  %out = call <vscale x 4 x i32> @llvm.aarch64.sve.mla.u.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> splat(i32 4), <vscale x 4 x i32> %x)
  ret <vscale x 4 x i32> %out
}

define <vscale x 4 x i32> @svmla_u_i32_by_8_commuted(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x) {
; CHECK-LABEL: define <vscale x 4 x i32> @svmla_u_i32_by_8_commuted(
; CHECK-SAME: <vscale x 4 x i1> [[PG:%.*]], <vscale x 4 x i32> [[A:%.*]], <vscale x 4 x i32> [[X:%.*]]) {
; CHECK-NEXT:    [[OUT:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.mla.u.nxv4i32(<vscale x 4 x i1> [[PG]], <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X]], <vscale x 4 x i32> splat (i32 8))
; CHECK-NEXT:    ret <vscale x 4 x i32> [[OUT]]
;
  %out = call <vscale x 4 x i32> @llvm.aarch64.sve.mla.u.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> splat(i32 8), <vscale x 4 x i32> %x)
  ret <vscale x 4 x i32> %out
}

declare <vscale x 4 x i32> @llvm.aarch64.sve.mul.u.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.mla.u.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
